<a href="https://colab.research.google.com/github/RithwikMohan/ML_Lab/blob/main/ML.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

23-07-25

In [ ]:
#9
import pandas as pd
data={
    2014:[100.5,150.8,200.9,30000,40000],
    2015:[12000,18000,22000,30000,45000],
    2016:[20000,50000,70000,100000,125000],
    2017:[50000,60000,70000,80000,90000]
}
df=pd.DataFrame(data,index=['Madhu','Kusum','Kinshuk','Ankit','Shruti'])
print(df)

            2014   2015    2016   2017
Madhu      100.5  12000   20000  50000
Kusum      150.8  18000   50000  60000
Kinshuk    200.9  22000   70000  70000
Ankit    30000.0  30000  100000  80000
Shruti   40000.0  45000  125000  90000


28-07-25

In [ ]:
#10
import pandas as pd

print(df.index)
print(df.columns)
print(df.dtypes)
print(df.ndim)
print(df.shape)
print(df.size)
print(df.values)
print(df.tail(2))
print(df.iloc[:,:2])
new_data={2018:[160000,110000,50000,340000,90000]}
sales2=pd.DataFrame(new_data,index=['Madhu','Kusum','Kinshuk','Ankit','Shruti'])
print(sales2)
print(sales2.empty)

Index(['Madhu', 'Kusum', 'Kinshuk', 'Ankit', 'Shruti'], dtype='object')
Index([2014, 2015, 2016, 2017], dtype='int64')
2014    float64
2015      int64
2016      int64
2017      int64
dtype: object
2
(5, 4)
20
[[1.005e+02 1.200e+04 2.000e+04 5.000e+04]
 [1.508e+02 1.800e+04 5.000e+04 6.000e+04]
 [2.009e+02 2.200e+04 7.000e+04 7.000e+04]
 [3.000e+04 3.000e+04 1.000e+05 8.000e+04]
 [4.000e+04 4.500e+04 1.250e+05 9.000e+04]]
           2014   2015    2016   2017
Ankit   30000.0  30000  100000  80000
Shruti  40000.0  45000  125000  90000
            2014   2015
Madhu      100.5  12000
Kusum      150.8  18000
Kinshuk    200.9  22000
Ankit    30000.0  30000
Shruti   40000.0  45000
           2018
Madhu    160000
Kusum    110000
Kinshuk   50000
Ankit    340000
Shruti    90000
False


In [15]:
#11
sales=pd.concat([df,sales2],axis=1)
print(sales)
print(sales.transpose())
print(sales[2017])
print(sales.loc[["Madhu",'Ankit'],[2017,2018]]) #sales made by madhu and ankith in 2017 and 2018
print(sales.loc[["Shruti"],[2016]])

sales = sales.loc[:, ~sales.columns.duplicated()] #ignore this
sales.loc["Sumeet"] = [196.2, 37800, 52000, 78438, 38852]
print(sales)

sales.drop([2014], axis=1, inplace=True) #Dropping 2014 row from sales, inplace will update the same dataframe instead of creating another, for col axis=1
print(sales)

sales.drop(['Kinshuk'], axis=0, inplace=True) #Dropping Kinshuk from sales, for row axis=0
print(sales)

sales.rename(index = {'Ankit' : 'Vivaan',
                      'Madhu' : 'Shailesh'}, inplace=True )
print(sales)

sales.loc[['Shailesh'],[2018]] = 100000
print(sales)

#Exporting data into csv file
sales.to_csv("SalesFigures.csv", index=False, header=False)


# Step 1: Read the CSV file into SalesRetrieved
SalesRetrieved = pd.read_csv('SalesFigures.csv', header=None)

# Step 2: Display SalesRetrieved before updating labels
print("Before updating labels:\n", SalesRetrieved)

# Step 3: Update the row and column labels to match Sales
SalesRetrieved.index = sales.index
SalesRetrieved.columns = sales.columns

# Step 4: Display SalesRetrieved after updating labels
print("\nAfter updating labels:\n", SalesRetrieved)


            2014   2015    2016   2017    2018
Madhu      100.5  12000   20000  50000  160000
Kusum      150.8  18000   50000  60000  110000
Kinshuk    200.9  22000   70000  70000   50000
Ankit    30000.0  30000  100000  80000  340000
Shruti   40000.0  45000  125000  90000   90000
         Madhu     Kusum  Kinshuk     Ankit    Shruti
2014     100.5     150.8    200.9   30000.0   40000.0
2015   12000.0   18000.0  22000.0   30000.0   45000.0
2016   20000.0   50000.0  70000.0  100000.0  125000.0
2017   50000.0   60000.0  70000.0   80000.0   90000.0
2018  160000.0  110000.0  50000.0  340000.0   90000.0
Madhu      50000
Kusum      60000
Kinshuk    70000
Ankit      80000
Shruti     90000
Name: 2017, dtype: int64
        2017    2018
Madhu  50000  160000
Ankit  80000  340000
          2016
Shruti  125000
            2014     2015      2016     2017      2018
Madhu      100.5  12000.0   20000.0  50000.0  160000.0
Kusum      150.8  18000.0   50000.0  60000.0  110000.0
Kinshuk    200.9  22000.0 

29-07-25

excercise-**2**

In [19]:
#13
import pandas as pd

data = {
    'Item': ['TV', 'TV', 'TV', 'AC'],
    'Company': ['LG', 'VIDEOCON', 'LG', 'SONY'],
    'Rupees': [12000, 10000, 15000, 14000],
    'USD': [700, 650, 800, 750]
}

df = pd.DataFrame(data)
print(df)

new_rows = pd.DataFrame({
    'Item': ['Fridge', 'AC'],
    'Company': ['LG', 'Samsung'],
    'Rupees': [25000, 13000],
    'USD': [1200, 700]
})

df = pd.concat([df, new_rows], ignore_index=True)
print(df)


  Item   Company  Rupees  USD
0   TV        LG   12000  700
1   TV  VIDEOCON   10000  650
2   TV        LG   15000  800
3   AC      SONY   14000  750
     Item   Company  Rupees   USD
0      TV        LG   12000   700
1      TV  VIDEOCON   10000   650
2      TV        LG   15000   800
3      AC      SONY   14000   750
4  Fridge        LG   25000  1200
5      AC   Samsung   13000   700

Maximum price of LG TV (Rupees): 15000


ignore_index=True
🔍 What it does:
When you're concatenating, appending, or resetting index in a DataFrame, using ignore_index=True tells pandas to:

Reset the row index to a default 0, 1, 2, ... sequence

Ignore the existing index values
    Name
0  Alice
1    Bob
0 Charlie
1  David   ← duplicate row indices!

✅ With ignore_index=True:
result2 = pd.concat([df1, df2], ignore_index=True)
print(result2)
Output:
     Name
0   Alice
1     Bob
2  Charlie
3   David

In [21]:
#To display the maximum price of LG TV.
max_price_lg_tv = df[(df['Item'] == 'TV') & (df['Company'] == 'LG')]['Rupees'].max()
print("Maximum price of LG TV (Rupees):", max_price_lg_tv)


Maximum price of LG TV (Rupees): 15000


In [25]:
#d) To display the Sum of all products.
sum_rupees = df['Rupees'].sum()
sum_usd = df['USD'].sum()

print("\nSum of all products in Rupees:", sum_rupees)
print("Sum of all products in USD:", sum_usd)



Sum of all products in Rupees: 89000
Sum of all products in USD: 4800


In [28]:
#To display the median of the USD of Sony products.
median_usd_sony = df[df['Company'] == 'SONY']['USD'].median()
print("Median USD of SONY products:", median_usd_sony)

Median USD of SONY products: 750.0


In [33]:
#14
import pandas as pd
import numpy as np

# a) Create the DataFrame
data = {
    'Name': ['Amit', 'Riya', 'Karan', 'Sneha', 'Rahul', 'Neha'],
    'Degree': ['MBA', 'BCA', 'BCA', 'MBA', 'BCA', 'MBA'],
    'Stream': ['Finance', 'IT', 'IT', 'HR', 'IT', 'Finance'],
    'Marks': [85, 76, np.nan, 88, 76, 92]
}

df = pd.DataFrame(data)
print(df)

# b) Print the Degree and maximum marks in each stream
print("\nb) Maximum marks in each stream:")
print(df.groupby(['Degree', 'Stream'])['Marks'].max())

# c) Fill the NaN with 76
df['Marks'] = df['Marks'].fillna(76)
# d) Set the index to Name
df.set_index('Name', inplace=True)

# e) Display name and degree-wise average marks of each student
print("\ne) Average marks name and degree-wise:")
print(df.groupby(['Name', 'Degree'])['Marks'].mean())

# f) Count the number of students in MBA
mba_count = (df['Degree'] == 'MBA').sum()
print("\nf) Number of students in MBA:", mba_count)

# g) Print the mode marks of BCA
bca_mode = df[df['Degree'] == 'BCA']['Marks'].mode()[0]
print("\ng) Mode marks of BCA students:", bca_mode)


    Name Degree   Stream  Marks
0   Amit    MBA  Finance   85.0
1   Riya    BCA       IT   76.0
2  Karan    BCA       IT    NaN
3  Sneha    MBA       HR   88.0
4  Rahul    BCA       IT   76.0
5   Neha    MBA  Finance   92.0

b) Maximum marks in each stream:
Degree  Stream 
BCA     IT         76.0
MBA     Finance    92.0
        HR         88.0
Name: Marks, dtype: float64

e) Average marks name and degree-wise:
Name   Degree
Amit   MBA       85.0
Karan  BCA       76.0
Neha   MBA       92.0
Rahul  BCA       76.0
Riya   BCA       76.0
Sneha  MBA       88.0
Name: Marks, dtype: float64

f) Number of students in MBA: 3

g) Mode marks of BCA students: 76.0
